# Claude Flow Production Pipeline Configuration
# This pipeline orchestrates the complete production-ready development

name: wildfly-flyway-production-pipeline
description: Transform WildFly Flyway subsystem to production-ready state

stages:
  - name: analysis
    parallel: true
    agents: 2
    tasks:
      - id: code-analysis
        description: Analyze current codebase for gaps
        focus: ["coverage", "complexity", "security"]
      - id: dependency-audit
        description: Audit all dependencies for vulnerabilities
        tools: ["maven", "owasp-check"]

  - name: core-development
    parallel: true
    agents: 4
    tasks:
      - id: testing-framework
        description: Implement comprehensive test suite
        priority: critical
        subtasks:
          - unit-tests
          - integration-tests
          - performance-tests
      - id: feature-completion
        description: Complete all missing features
        priority: high
        subtasks:
          - multi-datasource
          - migration-callbacks
          - jmx-monitoring
      - id: security-hardening
        description: Implement security measures
        priority: critical
        subtasks:
          - credential-encryption
          - rbac-implementation
          - audit-logging

  - name: operations
    parallel: true
    agents: 2
    tasks:
      - id: monitoring
        description: Add monitoring and observability
        components:
          - health-checks
          - metrics-collection
          - logging-framework
      - id: management
        description: WildFly management integration
        components:
          - cli-commands
          - web-console
          - jmx-beans

  - name: quality-assurance
    parallel: false
    agents: 2
    tasks:
      - id: test-execution
        description: Run all test suites
        gates:
          - coverage: 80
          - security: no-critical
          - performance: baseline-met
      - id: integration-testing
        description: Test with multiple databases
        databases: ["h2", "postgresql", "mysql", "oracle"]

  - name: documentation
    parallel: true
    agents: 2
    tasks:
      - id: user-documentation
        outputs:
          - README.md
          - CONFIGURATION.md
          - MIGRATION-GUIDE.md
      - id: developer-documentation
        outputs:
          - API-REFERENCE.md
          - CONTRIBUTING.md
          - ARCHITECTURE.md

  - name: release-preparation
    parallel: false
    agents: 1
    tasks:
      - id: build-artifacts
        description: Prepare release artifacts
        outputs:
          - maven-central-bundle
          - docker-images
          - feature-pack
      - id: release-validation
        description: Validate release readiness
        checks:
          - signatures
          - checksums
          - compatibility

pipeline:
  timeout: 3h
  retries: 2
  notifications:
    - on: failure
      message: "Pipeline failed at stage: {{stage}}"
    - on: success
      message: "Production pipeline completed successfully"

quality-gates:
  mandatory:
    - test-coverage: 80
    - security-vulnerabilities: 0
    - build-success: true
    - documentation-complete: true
  recommended:
    - performance-improvement: 10
    - code-duplication: <5%