name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    
    - name: Build project
      run: mvn clean install -B -DskipTests
    
    - name: Run tests
      run: mvn verify -B
    
    - name: Create Release Archive
      run: |
        mkdir -p release
        cp feature-pack/target/wildfly-flyway-feature-pack-*.zip release/
        cp subsystem/target/wildfly-flyway-subsystem-*.jar release/
        cd release && zip -r ../wildfly-flyway-${{ github.ref_name }}.zip * && cd ..
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          wildfly-flyway-${{ github.ref_name }}.zip
          release/wildfly-flyway-feature-pack-*.zip
          release/wildfly-flyway-subsystem-*.jar
        generate_release_notes: true
        draft: false
        prerelease: false